import type {
  Agent,
  AllowedUser,
  DomainMemory,
  Room,
  RoomMembership,
  UserProfile,
} from "@/types/domain";

const now = "2026-05-08T00:00:00.000Z";

export const mockUser: UserProfile = {
  userId: "00000000-0000-4000-8000-000000000001",
  email: "admin@example.com",
  displayName: "총괄 관리자",
  avatarUrl: null,
  isAdmin: true,
  createdAt: now,
  updatedAt: now,
};

export const rooms: Room[] = [
  {
    id: "meeting",
    name: "메인 회의방",
    type: "meeting",
    icon: "🏛️",
    description: "모든 팀원이 모이고, 각 방의 봇이 잠시 입장하는 협업 허브입니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 0,
    layoutX: 2,
    layoutY: 2,
    isActive: true,
    createdAt: now,
  },
  {
    id: "finance",
    name: "재무",
    type: "department",
    icon: "💰",
    description: "예산, 정산, 지출 근거와 비용 추적을 관리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 1,
    layoutX: 1,
    layoutY: 1,
    isActive: true,
    createdAt: now,
  },
  {
    id: "planning",
    name: "기획",
    type: "department",
    icon: "📋",
    description: "운영 일정, 회의 안건, 과제 로드맵을 정리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 2,
    layoutX: 2,
    layoutY: 1,
    isActive: true,
    createdAt: now,
  },
  {
    id: "external",
    name: "대외협력",
    type: "department",
    icon: "🤝",
    description: "기관 협의, 공문, 협력 제안 흐름을 관리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 3,
    layoutX: 3,
    layoutY: 1,
    isActive: true,
    createdAt: now,
  },
  {
    id: "development",
    name: "개발",
    type: "department",
    icon: "💻",
    description: "권한, DB, 운영, 오류 대응, 비용과 로그를 관리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 4,
    layoutX: 1,
    layoutY: 3,
    isActive: true,
    createdAt: now,
  },
  {
    id: "research",
    name: "연구",
    type: "department",
    icon: "🔬",
    description: "교육과정 분석, 수업 연구, 자료 분석과 루브릭을 다룹니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 5,
    layoutX: 2,
    layoutY: 3,
    isActive: true,
    createdAt: now,
  },
  {
    id: "promotion",
    name: "홍보",
    type: "department",
    icon: "📣",
    description: "발표자료, 홍보 문안, 시각화 산출물을 만듭니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 6,
    layoutX: 3,
    layoutY: 3,
    isActive: true,
    createdAt: now,
  },
  {
    id: "city_research",
    name: "시교육연구회 과제",
    type: "project",
    icon: "🏫",
    description: "시교육연구회 과제 산출물과 제출 흐름을 관리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 7,
    layoutX: 1,
    layoutY: 4,
    isActive: true,
    createdAt: now,
  },
  {
    id: "province_research",
    name: "도교육연구회 과제",
    type: "project",
    icon: "🏢",
    description: "도교육연구회 과제 산출물과 협의 내용을 관리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 8,
    layoutX: 2,
    layoutY: 4,
    isActive: true,
    createdAt: now,
  },
  {
    id: "science_museum",
    name: "과학관 과제",
    type: "project",
    icon: "🔭",
    description: "과학관 협력 과제, 전시/체험 운영 자료를 정리합니다.",
    defaultModel: "claude-sonnet-4-5",
    displayOrder: 9,
    layoutX: 3,
    layoutY: 4,
    isActive: true,
    createdAt: now,
  },
];

const botNames: Record<string, string> = {
  finance: "재무봇",
  planning: "기획봇",
  external: "대외협력봇",
  development: "개발봇",
  research: "연구봇",
  promotion: "홍보봇",
  city_research: "시교육봇",
  province_research: "도교육봇",
  science_museum: "과학관봇",
};

export const agents: Agent[] = rooms
  .filter((room) => room.id !== "meeting")
  .map((room) => ({
    id: `${room.id}_bot`,
    roomId: room.id,
    name: botNames[room.id],
    role: `${room.name} 업무를 총괄하는 도메인 봇`,
    anthropicAgentId: null,
    anthropicEnvironmentId: null,
    defaultModel: room.defaultModel ?? "claude-sonnet-4-5",
    systemPrompt: `${room.name} 업무를 총괄한다. 개인정보와 민감정보를 무단 공유하지 않고, 불확실한 내용은 확인 질문으로 남긴다.`,
    guestPrompt: "회의방에서는 5문장 이내로 출처와 다음 행동을 포함해 브리핑한다.",
    isActive: true,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  }));

export const allowedUsers: AllowedUser[] = [
  {
    email: mockUser.email,
    invitedBy: null,
    invitedAt: now,
    notes: "Mock admin. 실제 운영 전 관리자 이메일로 교체하세요.",
    isActive: true,
    isAdmin: true,
  },
];

export const memberships: RoomMembership[] = rooms.map((room) => ({
  userId: mockUser.userId,
  roomId: room.id,
  role: "admin",
  joinedAt: now,
}));

export const baseMemories: DomainMemory[] = rooms.map((room) => ({
  roomId: room.id,
  summary:
    room.id === "meeting"
      ? "회의방은 공유 카드, 게스트 봇 브리핑, 결정사항, 화상회의 결과물을 모으는 허브입니다."
      : `${room.name} 방은 아직 실제 데이터 연결 전이며 mock 요약으로 표시됩니다.`,
  activeTasks: [],
  decisions: [],
  keyFacts: [],
  pendingContext: [],
  processedContext: [],
  metadata: {},
  updatedAt: now,
  updatedByAgentRun: null,
}));
